spring:
  datasource:
    url: jdbc:mysql://localhost:3306/NewsSubscribe
    username: root
    password: qwe123
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: 95eksldpf@gmail.com
    password: xhewdtoqqsoymtay
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
