apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argo-rollouts-config-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["argo-rollouts-config"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argo-rollouts-config-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: argo-rollouts
    namespace: default
roleRef:
  kind: Role
  name: argo-rollouts-config-role
  apiGroup: rbac.authorization.k8s.io
