apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
        version: v1.0.1
    spec:
      containers:
        - name: spring-app
          image: 635140758252.dkr.ecr.ap-northeast-2.amazonaws.com/spring-app:v1.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          envFrom:
            - secretRef:
                name: spring-secret
  strategy:
    blueGreen:
      activeService: spring-active
      previewService: spring-preview
      autoPromotionEnabled: true
