apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
        - name: spring-app
          image: ecr-repo-url  # GitHub Actions에서 sed로 치환됨
          ports:
            - containerPort: 8080
#          readinessProbe:
#            httpGet:
#              path: /actuator/health
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 10
          envFrom:
            - secretRef:
                name: spring-secret
  strategy:
    blueGreen:
      activeService: spring-active
      previewService: spring-preview
      autoPromotionEnabled: true  # ✅ readinessProbe 통과 후 자동 전환
